### ISSUE TITLE
Error when importing eventbrite object

### ISSUE THREAD

**Issue by millerf** [eventbrite/eventbrite-sdk-javascript#72]
Hi there,

I just installed a package on a CSR version of reactJS. Basically the server is running on node.js, and I get this error when `importing` the module:
```
import eventbrite from 'eventbrite';
```

Results on this error, both on front and back-end side:

```
Error: Cannot find module 'encoding'
    at webpackMissingModule (webpack-internal:///./node_modules/isomorphic-fetch/node_modules/node-fetch/lib/body.js:5:80)
    at eval (webpack-internal:///./node_modules/isomorphic-fetch/node_modules/node-fetch/lib/body.js:5:163)
    at Object../node_modules/isomorphic-fetch/node_modules/node-fetch/lib/body.js (/front/build/server.js:3410:1)
    at __webpack_require__ (/front/build/server.js:27:30)
    at eval (webpack-internal:///./node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:5:338)
    at Object../node_modules/isomorphic-fetch/node_modules/node-fetch/index.js (/front/build/server.js:3399:1)
    at __webpack_require__ (/front/build/server.js:27:30)
    at eval (webpack-internal:///./node_modules/isomorphic-fetch/fetch-npm-node.js:1:15)
    at Object../node_modules/isomorphic-fetch/fetch-npm-node.js (/front/build/server.js:3388:1)
    at __webpack_require__ (/front/build/server.js:27:30)
```

The strange thing is that I only IMPORT `evenbrite`, I am not even using it.

* Node version: running on docker container node:10-alpine
* Browser name and version: Any
* Operating system: **Docker**

**Comment by kwelch** [comment]
Can you send over a repro repo? 

I have a working codesandbox that uses either require or import, but I realize webpack resolution can be much different than codesandbox. 

Thanks

**Comment by emichips** [comment]
Same error to me for the same Docker env, Node 14

**Comment by emichips** [comment]
> Same error to me for the same Docker env, Node 14

I solved following this
https://dev.to/mukul_singhal/write-es6-in-node-using-babel-3m7p

Basically it can work thanks to Babel transpiler

**Comment by kwelch** [comment]
Thanks I appreciate the follow up.
